### ISSUE TITLE
Emoji regex doesn't capture the variation selector after textual symbols

### ISSUE THREAD

**Issue by rgrove** [milesj/emoji-database#1]
Thanks for this excellent resource! I've found it incredibly useful. I have run into one problem though.

The emoji regex doesn't capture the [`\uFE0F` variation selector](https://emojipedia.org/variation-selector-16/) that's used to indicate that a non-emoji character like `\u2764` (heavy black heart) should be treated as an emoji. Here's a simple repro case:

```js
const regex = require('emoji-database/regex');

'❤️'.match(regex);
// => [ '❤', index: 0, input: '❤️' ]
```

Here it is again with codepoint escapes instead of literal characters, in case your browser/OS combo actually renders a standalone `\u2764` as a red heart (Chrome on OS X doesn't, at least):

```js
const regex = require('emoji-database/regex');

'\u2764\uFE0F'.match(regex);
// => [ '\u2764', index: 0, input: '\u2764\uFE0F' ]
```

This issue seems to be present for all characters that don't have the Emoji_Presentation property (meaning that they default to a text representation rather than an emoji representation unless followed by `\uFE0F`).

The fix seems to be to match an optional `\uFE0F` at the end of the regex:

```js
const fixedRegex = new RegExp(require('emoji-database/regex').source + '\uFE0F?');

'❤️'.match(fixedRegex);
// => [ '❤️', index: 0, input: '❤️' ]
```

I could see an argument for not capturing `\uFE0F` by default since that may not always be desirable, so I wasn't sure if this was intentional or not. If it is intentional, it might be helpful to mention this caveat (and the workaround) in the readme.

Thanks again!

**Comment by milesj** [comment]
Thanks for pointing this out! 

The regex is currently built using `regexgen` and the literal unicode character: https://github.com/milesj/emoji-database/blob/master/src/bin/generate-regex.js#L35 And based on the attached image, it looks like the default unicode character is the text representation (like you pointed out):

<img width="306" alt="screen shot 2017-05-24 at 10 55 37 am" src="https://cloud.githubusercontent.com/assets/143744/26418031/a69c01f0-406f-11e7-86d1-67079eb37ecf.png">

Now the best way to solve this... quite tricky. I suppose the default regex pattern should match everything, including text and emoji representations. I could then add additional regex patterns that are text only, or emoji only, etc. Will have to dig a bit deeper.

**Comment by milesj** [comment]
This is fixed in the next version.

**Comment by rgrove** [comment]
Awesome! Thanks. 😄
