### ISSUE TITLE
Consider moving all dependencies to devDependencies

### ISSUE THREAD

**Issue by rgrove** [milesj/emoji-database#2]
As far as I can tell, none of the generated datasets or regexes actually rely on any of the production dependencies listed in `package.json`. Could they be moved to `devDependencies` to prevent them from being installed in production?

I ask because EmojiOne in particular is really huge (149MB!). In environments like Heroku where there are limits on how large an app and its dependencies can be, this is unfortunate.

I'd be happy to send a PR for this, but I wanted to make sure I'm not missing something first.

**Comment by milesj** [comment]
They're `dependencies` because you can use `packageData`, `extractSet`, and all the other helpers locally to generate your own datasets. Perhaps I should remove this functionality and just force people to use the pre-generated dumps.

**Comment by milesj** [comment]
I'm also looking into adding more data to [unicode-emoji-data](https://github.com/dematerializer/unicode-emoji-data/issues/7), in an effort to remove EmojiOne.

**Comment by milesj** [comment]
Went ahead and moved them all to dev deps.
